### ISSUE TITLE
boolean value wrong

### ISSUE THREAD

**Issue by chaojinn** [franslundberg/binson-java#2]
according to http://binson.org/
true       = %x44
false      = %x45
somehow in this library , it is reversed.
public static final int FALSE       = 0x44;
public static final int TRUE        = 0x45;
Please check if the website is wrong or the code is wrong.

**Comment by franslundberg** [comment]
Thank you! Well-spotted. This a bug in the binson-java implementation.

**Comment by franslundberg** [comment]
Fixed.
