### ISSUE TITLE
Probably, the bug when generating nested empty objects: {"":{"":{"":{}}}}

### ISSUE THREAD

**Issue by ppmag** [franslundberg/binson-java#22]
Pls try next code:
```Java
byte[] b = new Binson()
                         .put("", new Binson()
                                 .put("", new Binson())
                                        .put("", new Binson()))
                  .toBytes();

System.out.println("len: " + b.length + ", " + hex(b));
```

Result:
```
len: 10, "40140040140040414141"
```
When looking on above hexdump, it's easy to see innermost put() was skipped.

**Comment by franslundberg** [comment]
Needs to be verified. Could be a bug!

**Comment by franslundberg** [comment]
Labelled as "bug" for now since it is a potential actual bug.

**Comment by franslundberg** [comment]
This is *not* a bug. The problem is in the test code. Look at the parenthesis carefully! The empty Binson object is added twice with the same field name (""). The issue author should have written code that ends with "))))". Now it ends with ")))". Tricky to see.
