### ISSUE TITLE
Binson.fromBytes does not enforce field ordering

### ISSUE THREAD

**Issue by fgrape** [franslundberg/binson-java#6]
Parsing bytes with fields that are not in lexicographical order results in a successful parse. 

The following test case fails. obj.toBytes() results in a correctly serialized Binson object, with the fields in lexicographical order. Throwing a suitable exception is probably a good idea since the bytes are **not** a valid Binson serialization and should therefore not be parsed as such.

    @Test
    public void testFromBytesWithUnorderedFields() {
        byte[] unordered = {0x40, 
                     0x14, 0x01, 0x42, 0x14, 0x01, 0x42,  // "B": "B"
                     0x14, 0x01, 0x41, 0x14, 0x01, 0x42,  // "A": "A"
                     0x41};
        
        Binson obj = Binson.fromBytes(unordered);
        
        Assert.assertArrayEquals(unordered, obj.toBytes());
    }

And when parsing an object with duplicate fields the last duplicate field is the one present in the resulting Binson object. 

The following test case fails. obj.toBytes() results in a correctly serialized Binson object, but with fields "missing" from the input. Throwing a suitable exception is probably a good idea since the bytes are **not** a valid Binson serialization and should therefore not be parsed as such.

    @Test
    public void testFromBytesWithDuplicateFields() {
        byte[] duplicates = {0x40, 
                       0x14, 0x01, 0x42, 0x14, 0x01, 0x42,  // "B": "B"
                       0x14, 0x01, 0x42, 0x14, 0x01, 0x42,  // "B": "A"
                       0x41};
        
        Binson obj = Binson.fromBytes(duplicates); // { "B": "A" }
        
        Assert.assertArrayEquals(duplicates, obj.toBytes());
    }

**Comment by franslundberg** [comment]
I agree. I will change to strict parsing and make a new release.

**Comment by franslundberg** [comment]
Thanks for the good issue report :-)

**Comment by franslundberg** [comment]
Felix, is it OK for me to "steal" the code snippets in this issue for use in the project? Good examples.

**Comment by fgrape** [comment]
Of course!

**Comment by franslundberg** [comment]
Fixed.
